### PR TITLE
add change

### PR DESCRIPTION
**Pull request by sbeliakou**

### CODE REVIEW

**Comment by sbeliakou** [comment]
ANSIBLE0002 Trailing whitespace
playbook.yml:2


ANSIBLE0002 Trailing whitespace
playbook.yml:4
    myvar: "my_variable"

ANSIBLE0002 Trailing whitespace
playbook.yml:11
  - debug:

**Comment by sbeliakou** [comment]
```
ANSIBLE0002 Trailing whitespace
playbook.yml:2


ANSIBLE0002 Trailing whitespace
playbook.yml:4
    myvar: "my_variable"

ANSIBLE0002 Trailing whitespace
playbook.yml:11
  - debug:
```

**Comment by sbeliakou** [comment]
[playbook.yml](playbook.yml#L2) **ANSIBLE0002 Trailing whitespace**
```
2:    
```

[playbook.yml](playbook.yml#L4) **ANSIBLE0002 Trailing whitespace**
```
4:    myvar: "my_variable"
```

**Comment by sbeliakou** [comment]
test

**Comment by sbeliakou** [comment]
test

**Comment by sbeliakou** [comment]
test

**Comment by amazurenko** [comment]
test this please

**Pull request closed without merging**
